// Copyright 2024 Vladimir Kochnev. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file is generated by mkmach.go

#include "textflag.h"

TEXT	libc_mach_error_string_trampoline<>(SB),NOSPLIT,$0
	SUB	$16, RSP
	MOVD	R0, 0(RSP)
	MOVW	0(R0), R0	// error_value
	BL	libc_mach_error_string(SB)
	MOVD	0(RSP), R1
	MOVD	R0, 8(R1)
	ADD	$16, RSP
	RET

GLOBL	·libc_mach_error_string_trampoline_addr(SB), RODATA, $8
DATA	·libc_mach_error_string_trampoline_addr(SB)/8, $libc_mach_error_string_trampoline<>(SB)

TEXT	libc_mach_error_trampoline<>(SB),NOSPLIT,$0
	MOVW	8(R0), R1	// error_value
	MOVD	0(R0), R0	// str
	BL	libc_mach_error(SB)
	RET

GLOBL	·libc_mach_error_trampoline_addr(SB), RODATA, $8
DATA	·libc_mach_error_trampoline_addr(SB)/8, $libc_mach_error_trampoline<>(SB)
