// Copyright 2024 Vladimir Kochnev. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file is generated by mkmach.go

#include "textflag.h"

TEXT	libc_mach_error_string_trampoline<>(SB),NOSPLIT,$0
	PUSHQ	DI
	MOVL	0(DI), DI	// error_value
	CALL	libc_mach_error_string(SB)
	POPQ	DI
	MOVQ	AX, 8(DI)
	RET

GLOBL	·libc_mach_error_string_trampoline_addr(SB), RODATA, $8
DATA	·libc_mach_error_string_trampoline_addr(SB)/8, $libc_mach_error_string_trampoline<>(SB)

TEXT	libc_mach_error_trampoline<>(SB),NOSPLIT,$0
	MOVL	8(DI), SI	// error_value
	MOVQ	0(DI), DI	// str
	CALL	libc_mach_error(SB)
	RET

GLOBL	·libc_mach_error_trampoline_addr(SB), RODATA, $8
DATA	·libc_mach_error_trampoline_addr(SB)/8, $libc_mach_error_trampoline<>(SB)
